# Generated by Django 5.0.6 on 2024-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holati', models.CharField(choices=[('present', 'Mavjud'), ('absent', "Yo'q"), ('late', 'Kechikkan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sana', models.DateField()),
                ('holati', models.CharField(choices=[('paid', "To'langan"), ('pending', 'Kutilmoqda'), ('failed', 'Xato')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vazifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('muddati', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='YangilikVaElon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
