# Generated by Django 5.0.6 on 2024-06-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='oquvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oquvchi'),
        ),
        migrations.AddField(
            model_name='sinf',
            name='oqituvchi',
            field=models.ForeignKey(limit_choices_to={'roli': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='vazifa',
            name='sinfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sinf'),
        ),
    ]
