# Generated by Django 5.0.6 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
